export const colorList = [
  {
    title: '品牌色',
    colors: [
      {
        tokenKey: '--atom-color-brand-primary',
        label: '品牌主色',
        lightValue: '#165DFF',
        darkValue: '#3371FF',
      },
    ],
  },
  {
    title: '涨跌色',
    colors: [
      {
        tokenKey: '--atom-color-price-up',
        label: '美股涨幅-上涨',
        lightValue: '#009B67',
        darkValue: '#00A36D',
      },
      {
        tokenKey: '--atom-color-price-down',
        label: '美股涨幅-下跌',
        lightValue: '#FF381A',
        darkValue: '#FF4A2E',
      },
      {
        tokenKey: '--atom-color-price-crypto-up',
        label: '数字币涨幅-上涨',
        lightValue: '#2D0DD0',
        darkValue: '#29DFDF',
      },
      {
        tokenKey: '--atom-color-price-crypto-down',
        label: '数字币涨幅-下跌',
        lightValue: '#F9528F',
        darkValue: '#FD5695',
      },
      {
        tokenKey: '--atom-color-price-even',
        label: '美股涨幅-平、停牌、集合竞价',
        lightValue: '#000',
        darkValue: '#FFF',
      },
    ],
  },
  {
    title: '状态色',
    colors: [
      {
        tokenKey: '--atom-color-status-success',
        label: '成功',
        lightValue: '#009B67',
        darkValue: '#00A36D',
      },
      {
        tokenKey: '--atom-color-status-error',
        label: '失败、危险',
        lightValue: '#FF381A',
        darkValue: '#FF4A2E',
      },
      {
        tokenKey: '--atom-color-status-warning',
        label: '警告',
        lightValue: '#FFAA00',
        darkValue: '#FFB114',
      },
      {
        tokenKey: '--atom-color-status-info',
        label: '消息、通知',
        lightValue: '#165DFF',
        darkValue: '#3371FF',
      },
    ],
  },
  {
    title: '文字/图标颜色',
    colors: [
      {
        tokenKey: '--atom-color-text-primary',
        label: '一级文本色',
        lightValue: '#000',
        darkValue: '#FFF',
      },
      {
        tokenKey: '--atom-color-text-secondary',
        label: '二级文本色',
        lightValue: 'rgba(0, 0, 0, 0.6)',
        darkValue: 'rgba(255, 255, 255, 0.6)',
      },
      {
        tokenKey: '--atom-color-text-tertiary',
        label: '三级文本色',
        lightValue: 'rgba(0, 0, 0, 0.4)',
        darkValue: 'rgba(255, 255, 255, 0.4)',
      },
      {
        tokenKey: '--atom-color-text-quaternar',
        label: '四级文本色',
        lightValue: 'rgba(0, 0, 0, 0.2)',
        darkValue: 'rgba(255, 255, 255, 0.2)',
      },
      {
        tokenKey: '--atom-color-text-special',
        label: '特殊文本色',
        lightValue: 'rgba(0, 0, 0, 0.8)',
        darkValue: 'rgba(255, 255, 255, 0.8)',
      },
      {
        tokenKey: '--atom-color-text-inverse',
        label: '彩底白字/反色',
        lightValue: '#FFF',
        darkValue: '#FFF',
      },
      {
        tokenKey: '--atom-color-text-link',
        label: '文字链',
        lightValue: '#165DFF',
        darkValue: '#3371FF',
      },
      {
        tokenKey: '--atom-color-text-aime',
        label: '无处不在文字链',
        lightValue: '#165DFF',
        darkValue: '#8BAEFF',
      },
    ],
  },
  {
    title: '背景色',
    colors: [
      {
        tokenKey: '--atom-color-background-layer1',
        label: '页面一级背景色，最底层背景',
        lightValue: '#F2F2F2',
        darkValue: '#000',
      },
      {
        tokenKey: '--atom-color-foreground-layer1',
        label: '页面一级前景色，大卡等模块背景',
        lightValue: '#FFF',
        darkValue: '#171717',
      },
      {
        tokenKey: '--atom-color-foreground-layer1_2',
        label: '页面一级前景色，模块内卡片等背景',
        lightValue: '#F2F2F2',
        darkValue: '#292929',
      },
      {
        tokenKey: '--atom-color-foreground-layer1_3',
        label: '页面一级前景色，模块内卡片等背景',
        lightValue: '#FFF',
        darkValue: '#383838',
      },
      {
        tokenKey: '--atom-color-background-layer2',
        label: '页面二级背景色，浮层最底层背景',
        lightValue: '#F2F2F2',
        darkValue: '#000',
      },
      {
        tokenKey: '--atom-color-foreground-layer2',
        label: '页面二级前景色，大卡等模块背景',
        lightValue: '#FFF',
        darkValue: '#171717',
      },
      {
        tokenKey: '--atom-color-background-layer3',
        label: '页面三级背景色，弹窗最底层背景',
        lightValue: '#FFF',
        darkValue: '#171717',
      },
      {
        tokenKey: '--atom-color-background-layer4',
        label: '页面四级背景色，下拉菜单气泡底层背景',
        lightValue: '#FFF',
        darkValue: '#292929',
      },
      {
        tokenKey: '--atom-color-background-layer5',
        label: '基础黑白色背景',
        lightValue: '#FFF',
        darkValue: '#000',
      },
    ],
  },
  {
    title: '其他元素',
    colors: [
      {
        tokenKey: '--atom-color-background-mask-level1',
        label: '一级-新功能气泡引导',
        lightValue: 'rgba(0, 0, 0, 0.8)',
        darkValue: 'rgba(0, 0, 0, 0.8)',
      },
      {
        tokenKey: '--atom-color-background-mask-level2',
        label: '二级常用弹窗',
        lightValue: 'rgba(0, 0, 0, 0.6)',
        darkValue: 'rgba(0, 0, 0, 0.6)',
      },
      {
        tokenKey: '--atom-color-background-mask-level3',
        label: '三级下拉菜单遮罩',
        lightValue: 'rgba(0, 0, 0, 0.2)',
        darkValue: 'rgba(0, 0, 0, 0.2)',
      },
      {
        tokenKey: '--atom-color-background-weak',
        label: '输入框背景色等浅底灰色',
        lightValue: 'rgba(0, 0, 0, 0.05)',
        darkValue: 'rgba(255, 255, 255, 0.2)',
      },
      {
        tokenKey: '--atom-color-background-nav',
        label: '导航栏背景色',
        lightValue: '#FFF',
        darkValue: '#171717',
      },
      {
        tokenKey: '--atom-color-divider-level1',
        label: '一级分割线',
        lightValue: 'rgba(0, 0, 0, 0.2)',
        darkValue: 'rgba(255, 255, 255, 0.22)',
      },
      {
        tokenKey: '--atom-color-divider-level2',
        label: '二级分割线',
        lightValue: 'rgba(0, 0, 0, 0.1)',
        darkValue: 'rgba(255, 255, 255, 0.12)',
      },
      {
        tokenKey: '--atom-color-divider-level3',
        label: '三级分割线',
        lightValue: 'rgba(0, 0, 0, 0.05)',
        darkValue: 'rgba(255, 255, 255, 0.07)',
      },
      {
        tokenKey: '--atom-color-border-bt',
        label: '标签按钮描边颜色',
        lightValue: 'rgba(0, 0, 0, 0.2)',
        darkValue: 'rgba(255, 255, 255, 0.22)',
      },
    ],
  },
  {
    title: '基础灰阶',
    colors: [
      {
        tokenKey: '--atom-color-grey-97',
        label: '基础灰阶97',
        lightValue: '#F7F7F7',
        darkValue: '#080808',
      },
      {
        tokenKey: '--atom-color-grey-95',
        label: '基础灰阶95',
        lightValue: '#F2F2F2',
        darkValue: '#171717',
      },
      {
        tokenKey: '--atom-color-grey-90',
        label: '基础灰阶90',
        lightValue: '#E6E6E6',
        darkValue: '#292929',
      },
      {
        tokenKey: '--atom-color-grey-80',
        label: '基础灰阶80',
        lightValue: '#CCC',
        darkValue: '#383838',
      },
      {
        tokenKey: '--atom-color-grey-70',
        label: '基础灰阶70',
        lightValue: '#B3B3B3',
        darkValue: '#474747',
      },
      {
        tokenKey: '--atom-color-grey-60',
        label: '基础灰阶60',
        lightValue: '#999',
        darkValue: '#575757',
      },
      {
        tokenKey: '--atom-color-grey-50',
        label: '基础灰阶50',
        lightValue: '#808080',
        darkValue: '#666',
      },
      {
        tokenKey: '--atom-color-grey-40',
        label: '基础灰阶40',
        lightValue: '#666',
        darkValue: '#757575',
      },
      {
        tokenKey: '--atom-color-grey-20',
        label: '基础灰阶20',
        lightValue: '#333',
        darkValue: '#CCC',
      },
    ],
  },
  {
    title: '辅助色',
    colors: [
      {
        tokenKey: '--atom-color-blue',
        label: '品牌主色常态',
        lightValue: '#165DFF',
        darkValue: '#3371FF',
      },
      {
        tokenKey: '--atom-color-green',
        label: '品牌辅助色常态',
        lightValue: '#009B67',
        darkValue: '#00A36D',
      },
      {
        tokenKey: '--atom-color-red',
        label: '品牌辅助色常态',
        lightValue: '#FF381A',
        darkValue: '#FF4A2E',
      },
      {
        tokenKey: '--atom-color-orange',
        label: '品牌辅助色常态',
        lightValue: '#FF6600',
        darkValue: '#FF7214',
      },
      {
        tokenKey: '--atom-color-yellow',
        label: '品牌辅助色常态',
        lightValue: '#FFAA00',
        darkValue: '#FFB114',
      },
      {
        tokenKey: '--atom-color-cyan',
        label: '品牌辅助色常态',
        lightValue: '#00CCC3',
        darkValue: '#00D9CF',
      },
      {
        tokenKey: '--atom-color-acidblue',
        label: '品牌辅助色常态',
        lightValue: '#1A9FFF',
        darkValue: '#2EA7FF',
      },
      {
        tokenKey: '--atom-color-indigo',
        label: '品牌辅助色常态',
        lightValue: '#4443FF',
        darkValue: '#5B4DFF',
      },
      {
        tokenKey: '--atom-color-purple',
        label: '品牌辅助色常态',
        lightValue: '#B341D9',
        darkValue: '#B752D9',
      },
      {
        tokenKey: '--atom-color-gold',
        label: '品牌辅助色常态',
        lightValue: '#CCA670',
        darkValue: '#D9B077',
      },
    ],
  },
  {
    title: '辅助色透明',
    colors: [
      {
        tokenKey: '--atom-color-transparent-blue',
        label: '标签背景色',
        lightValue: 'rgba(22, 93, 255, 0.1)',
        darkValue: 'rgba(51, 113, 255, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-blue1',
        label: 'Aime解读卡片背景色',
        lightValue: 'rgba(22, 93, 255, 0.15)',
        darkValue: 'rgba(51, 113, 255, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-green',
        label: '标签背景色',
        lightValue: 'rgba(0, 155, 103, 0.1)',
        darkValue: 'rgba(0, 163, 109, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-red',
        label: '标签背景色',
        lightValue: 'rgba(255, 56, 26, 0.1)',
        darkValue: 'rgba(255, 74, 46, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-orange',
        label: '标签背景色',
        lightValue: 'rgba(255, 102, 0, 0.1)',
        darkValue: 'rgba(255, 114, 20, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-yellow',
        label: '标签背景色',
        lightValue: 'rgba(255, 170, 0, 0.1)',
        darkValue: 'rgba(255, 177, 20, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-cyan',
        label: '标签背景色',
        lightValue: 'rgba(0, 204, 195, 0.1)',
        darkValue: 'rgba(0, 217, 207, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-acidblue',
        label: '标签背景色',
        lightValue: 'rgba(26, 159, 255, 0.1)',
        darkValue: 'rgba(46, 167, 255, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-indigo',
        label: '标签背景色',
        lightValue: 'rgba(68, 51, 255, 0.1)',
        darkValue: 'rgba(91, 77, 255, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-purple',
        label: '标签背景色',
        lightValue: 'rgba(179, 65, 217, 0.1)',
        darkValue: 'rgba(183, 82, 217, 0.2)',
      },
      {
        tokenKey: '--atom-color-transparent-gold',
        label: '标签背景色',
        lightValue: 'rgba(204, 166, 112, 0.1)',
        darkValue: 'rgba(217, 176, 119, 0.2)',
      },
    ],
  },
  {
    title: '可视化',
    colors: [
      {
        tokenKey: '--atom-color-visualization-primary',
        label: '可视化色 - 默认折柱色',
        lightValue: '#265FFC',
        darkValue: '#265FFC',
      },
      {
        tokenKey: '--atom-color-visualization-01',
        label: '可视化色',
        lightValue: '#38D1FF',
        darkValue: '#38D1FF',
      },
      {
        tokenKey: '--atom-color-visualization-02',
        label: '可视化色',
        lightValue: '#F564B9',
        darkValue: '#F564B9',
      },
      {
        tokenKey: '--atom-color-visualization-03',
        label: '可视化色',
        lightValue: '#733ED6',
        darkValue: '#733ED6',
      },
      {
        tokenKey: '--atom-color-visualization-04',
        label: '可视化色',
        lightValue: '#00CCC3',
        darkValue: '#00CCC3',
      },
      {
        tokenKey: '--atom-color-visualization-05',
        label: '可视化色',
        lightValue: '#273D8F',
        darkValue: '#273D8F',
      },
      {
        tokenKey: '--atom-color-visualization-06',
        label: '可视化色',
        lightValue: '#FF7040',
        darkValue: '#FF7040',
      },
      {
        tokenKey: '--atom-color-visualization-07',
        label: '可视化色',
        lightValue: '#9EA9C7',
        darkValue: '#9EA9C7',
      },
      {
        tokenKey: '--atom-color-visualization-08',
        label: '可视化 0 轴颜色',
        lightValue: '#808080',
        darkValue: '#666',
      },
      {
        tokenKey: '--atom-color-visualization-09',
        label: '十字光标',
        lightValue: 'rgba(0, 0, 0, 0.6)',
        darkValue: 'rgba(255, 255, 255, 0.6)',
      },
      {
        tokenKey: '--atom-color-visualization-divider',
        label: '可视化网格线',
        lightValue: 'rgba(0, 0, 0, 0.1)',
        darkValue: 'rgba(255, 255, 255, 0.12)',
      },
      {
        tokenKey: '--atom-color-visualization-tooltip',
        label: '看板-背景',
        lightValue: '#EBEBEB',
        darkValue: '#383838',
      },
    ],
  },
  {
    title: '交互反馈',
    colors: [
      {
        tokenKey: '--atom-color-hover',
        label: 'Hover',
        lightValue: 'rgba(0, 0, 0, 0.05)',
        darkValue: 'rgba(255, 255, 255, 0.2)',
      },
      {
        tokenKey: '--atom-color-click',
        label: '点击',
        lightValue: 'rgba(0, 0, 0, 0.1)',
        darkValue: 'rgba(255, 255, 255, 0.25)',
      },
      {
        tokenKey: '--atom-color-hover-5%',
        label: 'Hover',
        lightValue: 'rgba(0, 0, 0, 0.05)',
        darkValue: 'rgba(255, 255, 255, 0.1)',
      },
      {
        tokenKey: '--atom-color-click-10%',
        label: '点击',
        lightValue: 'rgba(0, 0, 0, 0.1)',
        darkValue: 'rgba(255, 255, 255, 0.2)',
      },
    ],
  },
];